CREATE TABLE [dbo].[Usuario]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[LOGIN] VARCHAR(50) NOT NULL,
	[SENHA] INT NULL,
	[NOME] VARCHAR (50) NULL
)

CREATE TABLE [dbo].[Filme]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[TITULO] VARCHAR(50) NOT NULL,
	[ANO] INT NOT NULL,
	[ELENCO] VARCHAR(1000) NOT NULL,
	[IMDb_ID] VARCHAR(100) NULL,
	[DESCRICAO] VARCHAR(1000) NULL, 
)


CREATE TABLE [dbo].[Playlist]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[ID_USUARIO] INT NOT NULL,
	[ID_FILME] INT NOT NULL,
	CONSTRAINT [FK_Filme_ToPlaylist] FOREIGN KEY ([ID_FILME]) REFERENCES [Filme]([ID]),
	CONSTRAINT [FK_Usuario_ToPlaylist] FOREIGN KEY ([ID_USUARIO]) REFERENCES [Usuario]([ID])
)


